### PR TITLE
Updates email address of Petros in CONTRIBUTORS

### PR DESCRIPTION
**Pull request by petroseskinder**
Small nit.

### CODE REVIEW

**Comment by cgrushko** [comment]
@petroseskinder did you sign the CLA?
https://cla.developers.google.com/
I set a webhook to automatically check CLAs, but can't make it rescan existing PRs.

**Comment by petroseskinder** [comment]
Yeah, I have. I needed to so I could commit to the migration tooling.

**Comment by petroseskinder** [comment]
I have signed it.

**Comment by cgrushko** [comment]
I still don't see a signed CLA on file, but I'm pretty new to this, so I'm going to practice on you, if that's ok :)

Did you sign this in the past as an Individual Contributor, or were you included in a Corporate CLA in the past?

EDIT: I'm trying to verify with the GitHub username "petroseskinder"

**Comment by petroseskinder** [comment]
Yeah that sounds good with me. I previously used a corporate CLA. This is what github outputs when I try to sign as an individual contributor.

screen shot 2017-09-21 at 10 22 19 pm

**Comment by cgrushko** [comment]
Ok, here's the reason -
according to 
https://github.com/bazelbuild/BUILD_file_generator/commit/d94e271ef56db60612a92420038d431625846679.patch
you made this commit using `petroseskinder@users.noreply.github.com` which is not on file, so the CLA robot failed.

I verified you manually, thanks!

**Comment by petroseskinder** [comment]
Interesting. Let's try this again with another pull request. Let me find something to fix :)

**Pull request merged**
