### PR TITLE
Update reference to rules_scala

### PR DESCRIPTION
**Pull request by dslomov**
Fix for CI issue https://ci.bazel.build/blue/rest/organizations/jenkins/pipelines/Global/pipelines/BUILD_file_generator/runs/171/nodes/19/log/?start=0

### CODE REVIEW

**Review by cgrushko — APPROVED** [review]

**Comment by cgrushko** [comment]
Thanks!

**Comment by cgrushko** [comment]
retest this

**Comment by dslomov** [comment]
@cgrushko could you merge this please? 
(why do we have ci.bazel.io _and_ ci.bazel.build?)

**Comment by cgrushko** [comment]
I think they're both coming from the organization. If it has a settings page, I don't see it, so can't even tell for sure.

**Comment by dslomov** [comment]
@philwo for some reason, 'retest this' triggers testing on on both ci.bazel.io and ci.bazel.build, and the former hangs. Any thoughts?
(not a fan of how all mentions of CI results has disappeared from this thread after the merge)

**Comment by dslomov** [comment]
retest this

**Comment by philwo** [comment]
ci.bazel.io and ci.bazel.build are the exact same website - the former is a permanent HTTP redirect to the latter. Not sure how one of them could behave any differently. Let’s check it out at your desk when I’m in the office in a few minutes :)

**Pull request merged**
