### PR TITLE
Drop SourceFileResolver and use data from source code parsers.

### PR DESCRIPTION
**Pull request by cgrushko**
Also make a slight adjustment to the BFG <-> Parser protocol:
fileToRuleKind is a map, not a multimap.

### CODE REVIEW

**Comment by cgrushko** [comment]
@greggdonovan can't assign you to review this, so in case you want to...

**Review by petroseskinder — APPROVED** [review]
LGTM overall. 

Is there an example project that you are testing this on locally? That would be helpful for assessing changes moving forward. If not, I can set one up.

**Comment by cgrushko** [comment]
Unfortunately not yet...

**Comment by petroseskinder** [comment]
Wait, Carmi. We never ran the ci tests, i.e. "test please". Can you hold off on merging until those give us the green light?

**Comment by cgrushko** [comment]
According to https://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/PR/pipelines/BUILD_file_generator/runs/18/nodes/19/log/?start=0 from https://ci.bazel.io/blue/organizations/jenkins/PR%2FBUILD_file_generator/detail/BUILD_file_generator/18/pipeline/19 (linked on this page in "View details" on the merge message) I think the tests did run?
Do you get test failures locally?

**Comment by petroseskinder** [comment]
> I think the tests did run?

You're right. The logs are the source of truth. I was basing my claim on how we never explicitly asked jenkins to "test please."

**Comment by cgrushko** [comment]
I guess it's because you're a Collaborator with Write access, so no need
for 'test please'.

**Pull request merged**
