### PR TITLE
(#25) Update rules_scala to a version that supports Bazel 0.7.x.

### PR DESCRIPTION
**Pull request by greggdonovan**
Fix for [#25](https://github.com/bazelbuild/BUILD_file_generator/issues/25)

### CODE REVIEW

**Review by petroseskinder — APPROVED** [review]

**Comment by cgrushko** [comment]
Awesome, thanks!! :D

**Comment by petroseskinder** [comment]
@greggdonovan according to the CI, the change fails to build.

**Comment by greggdonovan** [comment]
Still failing in CI. Checking into it...

**Comment by greggdonovan** [comment]
Also seeing errors generating with bazel-deps:

```
gdonovan@3983:~/development/BUILD_file_generator (fix_rules_scala_with_bazel_0_7_0 *)$ ./dev-scripts/dependencies/generate.sh 
From https://github.com/johnynek/bazel-deps
 * branch            master     -> FETCH_HEAD
HEAD is now at b1c3502 add `--buildifier` option to `generate` to format BUILD files (fixes #73) (#90)
ERROR: /Users/gdonovan/development/bazel-deps/3rdparty/jvm/org/scala_lang/BUILD:14:1: in scala_library rule //3rdparty/jvm/org/scala_lang:scala_library: 
Traceback (most recent call last):
        File "/Users/gdonovan/development/bazel-deps/3rdparty/jvm/org/scala_lang/BUILD", line 14
                scala_library(name = 'scala_library')
        File "/private/var/tmp/_bazel_gdonovan/6fcac0fd900f6c0d2558c506b5c338d2/external/io_bazel_rules_scala/scala/scala.bzl", line 662, in _scala_library_impl
                _lib(ctx, True)
        File "/private/var/tmp/_bazel_gdonovan/6fcac0fd900f6c0d2558c506b5c338d2/external/io_bazel_rules_scala/scala/scala.bzl", line 633, in _lib
                create_java_provider(ctx, scalaattr, jars.transitive_comp...)
        File "/private/var/tmp/_bazel_gdonovan/6fcac0fd900f6c0d2558c506b5c338d2/external/io_bazel_rules_scala/scala/scala.bzl", line 566, in create_java_provider
                java_common.create_provider(ctx.actions, java_toolchain = ctx...., <4 more arguments>)
Output artifact 'external/scala/_ijar/scala-library/external/scala/lib/scala-library-ijar-ijar.jar' not under package directory '3rdparty/jvm/org/scala_lang' for target '//3rdparty/jvm/org/scala_lang:scala_library'.
ERROR: Analysis of target '//src/scala/com/github/johnynek/bazel_deps:parseproject_deploy.jar' failed; build aborted: Analysis of target '//3rdparty/jvm/org/scala_lang:scala_library' failed; build aborted.
INFO: Elapsed time: 0.159s
```
Investigating...

**Comment by greggdonovan** [comment]
There are two issues remaining to fix 0.7.0 support besides just updating `rules_scala`:

1. Update the version of `bazel-deps` to support 0.7.0. 
PR: https://github.com/johnynek/bazel-deps/pull/92

2. Either remove or update our `scala_import` and `declare_maven` rules with the changes to java providers. I will probably remove them for now to get the build to pass and open a separate issue to update them for 0.7.0.

**Comment by ittaiz** [comment]
Gregg,
I posted a newer version of scala_import which supports 0.7.0 in a WIP PR
of rules_scala

**Comment by greggdonovan** [comment]
Terrific -- thanks @ittaiz !

**Pull request merged**
