### PR TITLE
Fix use of javacopts to not modify the passed-in version.

### LINKED ISSUE #29: tools/bazel_defs/java.bzl is trying to modify a frozen variable
Detected in Bazel's CI system, logs at https://ci.bazel.io/blue/organizations/jenkins/Global%2FBUILD_file_generator/detail/BUILD_file_generator/61/pipeline/

The actual error is:
```
trying to mutate a frozen object
ERROR: /usr/local/google/home/jcater/repos/BUILD_file_generator/thirdparty/jvm/org/eclipse/platform/BUILD:99:1: Traceback (most recent call last):
	File "/usr/local/google/home/jcater/repos/BUILD_file_generator/thirdparty/jvm/org/eclipse/platform/BUILD", line 99
		java_library(name = "org_eclipse_equinox_pref...", <2 more arguments>)
	File "/usr/local/google/home/jcater/repos/BUILD_file_generator/tools/bazel_defs/java.bzl", line 70, in java_library
		javacopts += JAVACOPTS
```

And the source is https://github.com/bazelbuild/BUILD_file_generator/blob/cbf2640af10b153d25f029118e66602a8c870ed4/tools/bazel_defs/java.bzl#L70

### PR DESCRIPTION
**Pull request by katre**
Fixes #29.

### CODE REVIEW

**Review by greggdonovan — APPROVED** [review]
LGTM. Thanks for fixing this!

**Comment by greggdonovan** [comment]
test this please

**Comment by katre** [comment]
Jenkins, test this please.

**Comment by katre** [comment]
Jenkins, test this please

**Pull request merged**
