### PR TITLE
Remove config file for ci.bazel.io

### PR DESCRIPTION
**Pull request by meteorcloudy**
ci.bazel.io is not in use anymore, Bazel CI has switched to buildkite.
@greggdonovan

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@philwo Looks like even after removing the `.ci/` folder, `ci.bazel.io` is still in presubmit, how could I unlink it? Any idea?

**Review by greggdonovan — APPROVED** [review]

**Comment by petroseskinder** [comment]
why is ci.bazel.io still running?

**Comment by petroseskinder** [comment]
any thoughts @philwo

**Comment by meteorcloudy** [comment]
@philwo is on vacation, @fweikert  do you know how github presubmit is setup?

**Comment by meteorcloudy** [comment]
@fweikert is there a way to remove ci.bazel.io for presubmit?

**Comment by meteorcloudy** [comment]
@fweikert is there a way to remove ci.bazel.io for presubmit?

**Comment by fweikert** [comment]
buchgr@ and I had a brief look at the project settings (I don't have the necessary permissions), but we did not find out how the integration was configured.

**Comment by fweikert** [comment]
buchgr@ and I had a brief look at the project settings (I don't have the necessary permissions), but we did not find out how the integration was configured.

**Comment by philwo** [comment]
Fixed :D It was an old branch protection rule in the Settings that said that the "ci.bazel.io" status check *must* pass before it can be merged.

I removed it from there and picked the Buildkite check instead.

**Comment by meteorcloudy** [comment]
@philwo Thank you!!!

**Comment by meteorcloudy** [comment]
@petroseskinder Please merge this PR

**Pull request merged**
