### PR TITLE
#39 remove native http_archive

### PR DESCRIPTION
**Pull request by greggdonovan**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@petroseskinder Can we get this PR merged?

**Review by petroseskinder — APPROVED** [review]

**Comment by greggdonovan** [comment]
@meteorcloudy How can I get ci.bazel.io to clear or retry?

**Comment by meteorcloudy** [comment]
@greggdonovan `ci.bazel.io` is not in use anymore, we should just remove the `./.ci` folder.

**Comment by meteorcloudy** [comment]
@petroseskinder This one is also ready to be merged.

**Comment by petroseskinder** [comment]
@greggdonovan, can you rebase? I should be able to merge then

**Comment by greggdonovan** [comment]
@petroseskinder Rebased now. Thanks!

**Pull request merged**
