### PR TITLE
Add motivation and rudimentary running instructions to README.md

### PR DESCRIPTION
**Pull request by cgrushko**
Based on @petroseskinder 's https://github.com/bazelbuild/BUILD_file_generator/pull/24.

### CODE REVIEW

**Comment by cgrushko** [comment]
@spomorski I can't add you to the list of reviewers for some reason.
Let me know if that's no what you had in mind and I should add more.

**Comment by sergetron** [comment]
I think you or someone with permissions has to give me write access to that
repository.

**Review by sergetron — APPROVED** [review]

**Review by sergetron — COMMENTED** [review]
Disregard comment, I misread the commit. :)

**Comment by sergetron** [comment]
Disregard my last comment, I misread the commit. :)

**Comment by cgrushko** [comment]
@spomorski we recently discovered that there's some bug in BFG which makes it not work, so even with instructions it might not be good enough yet.

**Comment by sergetron** [comment]
Thanks for the info, any ETA on the fix?

**Comment by cgrushko** [comment]
Er... not yet :)

**Pull request merged**
