### PR TITLE
Update rules_scala

### PR DESCRIPTION
**Pull request by cushon**
bazelbuild/bazel#5483

### CODE REVIEW

**Review by lfpino — APPROVED** [review]

**Review by laszlocsomor — APPROVED** [review]

**Comment by lfpino** [comment]
Seems like @laszlocsomor can't approve either. @dslomov do you have any idea who can approve this?

**Review by dslomov — APPROVED** [review]

**Comment by dslomov** [comment]
Just did (using my bazelbuild organization superpowers)

**Comment by lfpino** [comment]
I'm somewhat sad I don't have those superpowers :(

**Comment by dslomov** [comment]
Superpowers are dangerous (you can accidentally do a destructive push) so we are are not giving them out much (I got those just a week ago out of necessity). 
The list of folks with write access to this repo is here: https://github.com/bazelbuild/BUILD_file_generator/settings/collaboration, so for larger changes they should be pinged to do the reviews.

**Comment by dslomov** [comment]
(and there is no way to give "approve but not write" permissions for the repo)

**Comment by petroseskinder** [comment]
I used to be able to approve... do i still have these permissions?

**Comment by lfpino** [comment]
I can't access https://github.com/bazelbuild/BUILD_file_generator/settings/collaboration, I'm actually not even getting emails from this thread.

**Comment by cushon** [comment]
@dslomov thanks for approving, can you also merge the PR? I'm not sure anyone else on the review has the necessary permissions.

**Comment by dslomov** [comment]
@petroseskinder yes you are listed as collaborator with write access to this repo

**Comment by dslomov** [comment]
> I can't access https://github.com/bazelbuild/BUILD_file_generator/settings/collaboration, 
I see, github ACL management is not awesome.

> I'm actually not even getting emails from this thread.
That is weird - I think you can probably set that up in GutHub settings

**Pull request merged**
