### PR TITLE
Move Java parser into a new lang/ directory

### PR DESCRIPTION
**Pull request by cgrushko**
for language-specific parsers.

### CODE REVIEW

**Comment by petroseskinder** [comment]
LGTM. 

It does seem a little redundant to move it to BUILD_file_generator/lang/java/src/test/**java**/com/google/devtools/build/bfg if you are going to rather than BUILD_file_generator/lang/java/src/test/com/google/devtools/build/bfg.

**Review by petroseskinder — APPROVED** [review]
LGTM. 

It does seem a little redundant to move it to BUILD_file_generator/lang/
java/src/test/**java**/com/google/devtools/build/bfg if you are going to
rather than BUILD_file_generator/lang/java/src/test/com/google/
devtools/build/bfg.

**Comment by petroseskinder** [comment]
test please

**Comment by cgrushko** [comment]
I have a prototype Go resolver for Java, so perhaps this extra level will
come handy eventually.

On Oct 12, 2017 10:05, "Petros Eskinder" <notifications@github.com> wrote:

*@petroseskinder* approved this pull request.

LGTM.

It does seem a little redundant to move it to BUILD_file_generator/lang/
java/src/test/*java*/com/google/devtools/build/bfg if you are going to
rather than BUILD_file_generator/lang/java/src/test/com/google/
devtools/build/bfg.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/BUILD_file_generator/pull/20#pullrequestreview-68935439>,
or mute the thread

**Comment by petroseskinder** [comment]
> I have a prototype Go resolver for Java, so perhaps this extra level will
come handy eventually.

Yay! Lets "Go"!

**Comment by cgrushko** [comment]
retest this please

**Comment by cgrushko** [comment]
Also... I kinda prefer merging my own PRs. Maybe because that's how it's done in Google :)

**Comment by petroseskinder** [comment]
Noted.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by greggdonovan** [comment]
LGTM

We should add usage documentation for the `JavaSourceFileParserCli` and the `BFG`. I'll make an issue.

**Pull request merged**
